import { prisma } from "../lib/prisma.js";

// Demo products shown in the storefront.
const SEED_PRODUCTS = [
  {
    name: "iPhone 16 Pro Max 256GB Titanium",
    category: "electronics",
    price: 1099.0,
    originalPrice: 1199.0,
    stock: 15,
    status: "active",
    rating: 4.9,
    reviewsCount: 1420,
    arrival: true,
    isSale: true,
    images: [
      "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Forged in grade-5 titanium with a revolutionary micro-blasted finish.",
    specs: { Display: "6.9-inch Super Retina XDR OLED", Chipset: "Apple A18 Pro" },
  },
  {
    name: "Samsung Galaxy S24 Ultra 12GB Titanium Gray",
    category: "electronics",
    price: 999.99,
    originalPrice: 1299.99,
    stock: 8,
    status: "active",
    rating: 4.8,
    reviewsCount: 1200,
    arrival: false,
    isSale: true,
    images: ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80"],    description: "Meet Galaxy S24 Ultra powered by Galaxy AI.",
    specs: { Display: "6.8-inch Dynamic AMOLED 2X", "S-Pen": "Embedded" },
  },
  {
    name: "Nike Jordan Brooklyn Fleece Men's Hoodie",
    category: "fashion",
    price: 45.0,
    originalPrice: 65.0,
    stock: 24,
    status: "active",
    rating: 4.6,
    reviewsCount: 569,
    arrival: false,
    isSale: true,
    images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80"],
    description: "Midweight brushed fleece hoodie with iconic Jumpman branding.",
    specs: { Material: "80% Cotton / 20% Polyester", Fit: "Standard" },
  },
  {
    name: "Diamond Stud Earrings in 14K White Gold",
    category: "luxury",
    price: 299.0,
    originalPrice: 399.0,
    stock: 6,
    status: "active",
    rating: 4.9,
    reviewsCount: 1100,
    arrival: true,
    isSale: false,
    images: ["https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80"],
    description: "Elegant lab-grown diamond stud earrings in solid 14k white gold.",
    specs: { "Total Carat Weight": "1.00 ctw", Metal: "14K Solid White Gold" },
  },
  {
    name: "Premium ANC Wireless Headphones (Rose Pink)",
    category: "electronics",
    price: 189.99,
    originalPrice: 249.99,
    stock: 12,
    status: "active",
    rating: 4.7,
    reviewsCount: 840,
    arrival: true,
    isSale: false,
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80"],
    description: "Hi-res wireless audio with dual noise canceling microphones.",
    specs: { Connectivity: "Bluetooth 5.3", "Battery Life": "40 hours" },
  },
  {
    name: "Designer Italian Leather Crossbody Bag",
    category: "luxury",
    price: 420.0,
    originalPrice: 550.0,
    stock: 3,
    status: "active",
    rating: 4.8,
    reviewsCount: 310,
    arrival: false,
    isSale: true,
    images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80"],
    description: "Handcrafted in Florence using full-grain pebbled calfskin.",
    specs: { Origin: "Made in Italy", Dimensions: "9.5W x 7H x 3.5D inches" },
  },
  {
    name: "Botanical Ceramic Vase & Dried Flower Set",
    category: "home",
    price: 38.5,
    originalPrice: 50.0,
    stock: 0,
    status: "out_of_stock",
    rating: 4.5,
    reviewsCount: 215,
    arrival: false,
    isSale: false,
    images: ["https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=800&q=80"],
    description: "Handcrafted matte ceramic vase with preserved eucalyptus.",
    specs: { Height: "8.5 inches", Finish: "Unglazed matte stoneware" },
  },
  {
    name: "Luminous Hydrating Glow Skincare Trio",
    category: "beauty",
    price: 64.0,
    originalPrice: 85.0,
    stock: 18,
    status: "active",
    rating: 4.9,
    reviewsCount: 650,
    arrival: true,
    isSale: false,
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80"],
    description: "3-step dermatologist-tested skincare routine.",
    specs: { "Skin Type": "All skin types", Formula: "Cruelty-free, Vegan" },
  },
  {
    name: "Fresh Organic Farm-to-Table Produce Basket",
    category: "groceries",
    price: 29.99,
    originalPrice: 35.0,
    stock: 10,
    status: "active",
    rating: 4.7,
    reviewsCount: 430,
    arrival: false,
    isSale: false,
    images: ["https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80"],
    description: "Curated weekly crate of pesticide-free local organic vegetables.",
    specs: { Weight: "10-12 lbs", Certification: "USDA Certified Organic" },
  },
  {
    name: "Beanless Bag Inflatable Velvet Lounge Chair",
    category: "home",
    price: 32.0,
    originalPrice: 48.0,
    stock: 4,
    status: "active",
    rating: 4.3,
    reviewsCount: 100,
    arrival: false,
    isSale: true,
    images: ["https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=800&q=80"],
    description: "Inflatable lounge chair with soft corduroy velvet feel.",
    specs: { Dimensions: "42in x 41in x 27in", "Weight Capacity": "220 lbs" },
  },
];

// Only seeds if the table is empty (idempotent).
export async function seedProducts(): Promise<void> {
  const count = await prisma.product.count();
  if (count === 0) {
    await prisma.product.createMany({ data: SEED_PRODUCTS });
    console.log(`Seeded ${SEED_PRODUCTS.length} products`);
  }
}
