import type { Icon as PhosphorIcon, IconProps as PhosphorIconProps } from "@phosphor-icons/react";
import {
  ArrowClockwise,  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowsClockwise,
  Armchair,
  Bank,
  Basket,
  BookOpen,
  Bookmark,
  BowlFood,
  CalendarBlank,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Check,
  CheckCircle,
  CircleNotch,
  Clock,
  CreditCard,
  Devices,
  Diamond,
  DownloadSimple,
  DotsThreeVertical,
  Envelope,
  Equalizer,
  Eye,
  EyeSlash,
  FacebookLogo,
  Fire,
  FlowerLotus,
  FunnelSimple,
  GameController,
  Gift,
  Headphones,
  Heart,
  House,
  Image,
  IdentificationBadge,
  Info,
  InstagramLogo,
  List,
  ListBullets,
  LockKey,
  MagicWand,
  MagnifyingGlass,
  MagnifyingGlassPlus,
  Minus,
  Money,
  Moon,
  Package,
  PencilSimple,
  Phone,
  Plus,
  Prohibit,
  SealCheck,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  ShoppingCartSimple,
  SignIn,
  SignOut,
  SlidersHorizontal,
  Sparkle,
  SquaresFour,
  Stack,
  Star,
  StarHalf,
  Storefront,
  Sun,
  Tag,
  Trash,
  TrashSimple,
  Truck,
  TShirt,
  User,
  UserCircle,
  UserPlus,
  UploadSimple,
  UsersThree,
  Wallet,
  Warning,
  WarningCircle,
  Watch,
  X,
  XLogo,
  YoutubeLogo,
} from "@phosphor-icons/react";

// Maps a snake_case name to a Phosphor icon component (used everywhere).
const ICON_MAP: Record<string, PhosphorIcon> = {
  account_balance: Bank,
  account_balance_wallet: Wallet,
  account_circle: UserCircle,
  add: Plus,
  add_shopping_cart: ShoppingCartSimple,
  apparel: TShirt,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkle,
  auto_fix_high: MagicWand,
  badge: IdentificationBadge,
  block: Prohibit,
  book: BookOpen,
  bookmark: Bookmark,
  calendar_today: CalendarBlank,
  call: Phone,
  category: Tag,
  chair: Armchair,
  check: Check,
  check_circle: CheckCircle,
  checkroom: TShirt,
  chevron_left: CaretLeft,
  chevron_right: CaretRight,
  close: X,
  dark_mode: Moon,
  delete: Trash,
  delete_sweep: TrashSimple,
  devices: Devices,
  diamond: Diamond,
  download: DownloadSimple,
  dots_three_vertical: DotsThreeVertical,
  edit: PencilSimple,
  equalizer: Equalizer,
  error: WarningCircle,
  event: CalendarBlank,
  expand_less: CaretUp,
  expand_more: CaretDown,
  eye: Eye,
  eye_off: EyeSlash,
  facebook: FacebookLogo,
  favorite: Heart,
  filter_alt: SlidersHorizontal,
  filter_list: FunnelSimple,
  grid_view: SquaresFour,
  group: UsersThree,
  headphones: Headphones,
  home: House,
  info: Info,
  instagram: InstagramLogo,
  image: Image,
  inventory: Package,
  inventory_2: Stack,
  light_mode: Sun,
  loader: CircleNotch,
  local_atm: Money,
  local_fire_department: Fire,
  local_shipping: Truck,
  lock: LockKey,
  login: SignIn,
  logout: SignOut,
  loyalty: Gift,
  mail: Envelope,
  menu: List,
  north_east: ArrowUpRight,
  nutrition: BowlFood,
  payments: CreditCard,
  person: User,
  person_add: UserPlus,
  upload: UploadSimple,
  published_with_changes: ArrowsClockwise,
  refresh: ArrowClockwise,
  remove: Minus,
  schedule: Clock,
  search: MagnifyingGlass,
  search_off: MagnifyingGlass,
  shield: ShieldCheck,
  shopping_bag: ShoppingBag,
  shopping_basket: Basket,
  shopping_cart: ShoppingCart,
  shopping_cart_off: ShoppingCartSimple,
  spa: FlowerLotus,
  sports_esports: GameController,
  star: Star,
  star_half: StarHalf,
  storefront: Storefront,
  task_alt: CheckCircle,
  verified: SealCheck,
  verified_user: ShieldCheck,
  view_list: ListBullets,
  warning: Warning,
  watch: Watch,
  x_twitter: XLogo,
  youtube: YoutubeLogo,
  zoom_in: MagnifyingGlassPlus,
};

interface IconProps extends PhosphorIconProps {
  name: string;
  filled?: boolean;
}

export const Icon = ({ name, size = "1em", weight, className, filled, ...rest }: IconProps) => {
  const IconComponent = ICON_MAP[name] || SquaresFour;
  return <IconComponent size={size} weight={filled ? "fill" : weight || "regular"} className={className} {...rest} />;
};
